# Release Versions
#version: 1.4.1
# Pre-Release Versions
version: 1.4.1-build{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

before_build:
  - nuget restore .\NCalc.sln

build:
  project: NCalc.sln

after_test:
  - ps: .\nuget\pack.ps1

artifacts:
  - path: Evaluant.Calculator\bin\Release\NCalc.dll
    name: NCalc.dll
  - path: '**\NCalc*.nupkg'
